name: Lint
on: [push]
permissions:
    contents: read # to fetch code (actions/checkout)
jobs:
    lint-code:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18.x
                  cache: pnpm
            - run: 'pnpm i && pnpm run sync && pnpm run package && pnpm run lint'
